POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json
{
  "username": "admin",
  "password": "admin"
}
### Get auth token
### Admin token: Authorization: Basic YWRtaW46YWRtaW4=
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json
{
  "username": "kate19981",
  "password": "Kate19981!"
}

### Positive test: Admin can create new user with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate19988",
  "password": "Kate19988!",
  "role": "USER"
}

### Negative test: Admin can not create new user with blank username
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "   ",
  "password": "{{$random.alphanumeric(10)}}@",
  "role": "USER"
}

### Negative test: Admin can not create new user with username 2 or 16 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "ab",
  "password": "{{$random.alphanumeric(10)}}#",
  "role": "USER"
}

### Negative test: Admin can not create new user with username 2 or 16 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "abcdefghijklmnop",
  "password": "{{$random.alphanumeric(10)}}%",
  "role": "USER"
}

### Negative test: Admin can not create new user with username contains $%^&*()@# characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "$%^&*()@#",
  "password": "{{$random.alphanumeric(10)}}^",
  "role": "USER"
}

### Negative test: Admin can not create new user with blank password
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": " ",
  "role": "USER"
}

### Negative test: Admin can not create new user with password less than 8 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": "Aa1234&",
  "role": "USER"
}

### Negative test: Admin can not create new user with password without digits
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": "Aa&bbbbb",
  "role": "USER"
}

### Negative test: Admin can not create new user with password without one lower case character
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": "AAA&12345",
  "role": "USER"
}

### Negative test: Admin can not create new user with password without one upper case character
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": "abc45678$",
  "role": "USER"
}

### Negative test: Admin can not create new user with password without special character
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": "Aab45678",
  "role": "USER"
}

### Negative test: Admin can not create new user with password with spaces
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": "Qwerty1 #",
  "role": "USER"
}

### Negative test: Admin can not create new user with role not from list "ADMIN", "USER"
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.alphanumeric(10)}}",
  "password": "{{$random.alphanumeric(10)}}!",
  "role": "EDITOR"
}

### Negative test: Create user that already exists
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate1998",
  "password": "Kate1998!",
  "role": "USER"
}

### Positive test: Authorized user can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTg4OkthdGUxOTk4OCE=

### Positive test: Check account was created
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTg4OkthdGUxOTk4OCE=